# Generated by Django 6.1.1 on 2026-09-15 21:44

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imageninmueble',
            name='uq_imagen_inmueble_url',
        ),
        migrations.AddField(
            model_name='imageninmueble',
            name='archivo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.almacenamiento_imagenes, upload_to=core.models.ruta_imagen_inmueble, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='imageninmueble',
            name='url',
            field=models.URLField(blank=True, help_text='Solo si la foto ya está alojada en otro lado', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='imageninmueble',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('inmueble', 'url'), name='uq_imagen_inmueble_url'),
        ),
        migrations.AddConstraint(
            model_name='imageninmueble',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('archivo', ''), _negated=True), ('archivo__isnull', False)), models.Q(('url', ''), _negated=True), _connector='OR'), name='ck_imagen_tiene_origen'),
        ),
    ]
