# Generated by Django 6.1.1 on 2026-09-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_imageninmueble_uq_imagen_inmueble_url_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='imageninmueble',
            name='ck_imagen_tiene_origen',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('archivo', ''), _negated=True), ('archivo__isnull', False)), models.Q(('url', ''), _negated=True), _connector='OR'), name='ck_imagen_tiene_origen', violation_error_message='Subí una imagen o pegá una URL.'),
        ),
    ]
