"""
Django settings for mls project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo se usa una clave de relleno; en producción es obligatorio
# definir DJANGO_SECRET_KEY en el entorno.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-solo-para-desarrollo-no-usar-en-produccion',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = os.environ.get(
    'MLS_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1],testserver'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # GeoDjango (PostGIS)
    'django.contrib.gis',
    # Apps del proyecto
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mls.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mls.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('MLS_DB_NAME', 'mls_db'),
        'USER': os.environ.get('MLS_DB_USER', 'mls_user'),
        'PASSWORD': os.environ.get('MLS_DB_PASSWORD', 'mls_local_dev'),
        'HOST': os.environ.get('MLS_DB_HOST', 'localhost'),
        'PORT': os.environ.get('MLS_DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
    }
}

# GeoDjango en macOS (Homebrew): rutas explícitas a GEOS y GDAL.
GEOS_LIBRARY_PATH = os.environ.get(
    'GEOS_LIBRARY_PATH', '/opt/homebrew/opt/geos/lib/libgeos_c.dylib'
)
GDAL_LIBRARY_PATH = os.environ.get(
    'GDAL_LIBRARY_PATH', '/opt/homebrew/opt/gdal/lib/libgdal.dylib'
)



# Autenticación
# La identidad es el correo: ver core.models.Usuario

AUTH_USER_MODEL = 'core.Usuario'

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:panel'
LOGOUT_REDIRECT_URL = 'core:landing'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Archivos subidos (fotos de inmuebles)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# BunnyCDN
# Storage Zone = dónde se suben los archivos; Pull Zone = dominio que los sirve.
# Sin estas variables el proyecto guarda en MEDIA_ROOT y sigue funcionando.

BUNNY_STORAGE_ZONE = os.environ.get('BUNNY_STORAGE_ZONE', '')
BUNNY_STORAGE_KEY = os.environ.get('BUNNY_STORAGE_KEY', '')
# Vacío = Falkenstein (la región por defecto). Otras: 'ny', 'la', 'sg', 'br'…
BUNNY_REGION = os.environ.get('BUNNY_REGION', '')
BUNNY_PULL_ZONE = os.environ.get('BUNNY_PULL_ZONE', '')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
